[package]
name = "party_invites"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5"
diesel = { version = "1.4.5", features = ["postgres"] }
dotenv = "0.15.0"
twilio-rust = "0.1"
